### ISSUE TITLE
Assembly reference error when importing

### ISSUE THREAD

**Issue by dolphinsd** [VirgilSecurity/virgil-sdk-crypto-net#1]
Import latest library into project and see error as in screen attached.

![02b051e9c9c1db3c697f92d50bd64bfa](https://user-images.githubusercontent.com/3460517/44674655-146a9600-a9e3-11e8-8f2a-8be094c2fb35.png)

**Comment by unlim-it** [comment]
Hello @dolphinsd, thanks for your feedback.

The package has been fixed. Use the latest version of the Virgil.Crypto package (https://www.nuget.org/packages/Virgil.Crypto/).
